fm_elfinder:
  assets_path: /assets # chemin des fichiers JS
  instances:
    default:
      locale: fr # Langue
      editor: ckeditor # Editeur utilisé
      fullscreen: true # Taille d'affichage
      connector:
        roots:
          uploads:
            driver: LocalFileSystem
            path: uploads
            upload_allow: ["image/png", "image/jpg", "image/jpeg"] # Fichiers autorisés
            upload_deny: ["all"] # Fichiers interdits
            upload_max_size: 1M # Taille maximum
