# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  filter_sets:
    thumb:
      # adjust the image quality to 60%
      quality: 50

      # list of transformations to apply (the "filters")
      filters:
        thumbnail:
          size: [250, 100]

    medium:
      # adjust the image quality to 75%
      quality: 70
      # list of transformations to apply (the "filters")
      filters:
        thumbnail:
          size: [800, 200]
          mode: outbond
