#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /about
    controller: App\Controller\HomeController::index
apropos:
    path: /apropos
    controller: App\Controller\HomeController::apropos

contact:
    path: /contact
    controller: App\Controller\HomeController::contact    
