index:
   path: /
   controller: App\Controller\BibliothequeController::index
#index:
#    path: /accueil
#    controller: App\Controller\HomeController::index
#apropos:
 #   path: /apropos
  #  controller: App\Controller\HomeController::apropos

    #mec:
     #   path: /mec
      #  controller: App\Controller\MecController::mecmec

# demarrage:
#     path: /
#     controller: App\Controller\ArticlesController::demarrage

      